Make CI failure a blocker
input-output-hk/cardano-sl-style-guides pull request #8
Opened 2017-06-22 22:17 UTC by manpages

Ditto.
@domenkozar and @georgeee please provide feedback.
Also, Domen, I'd like to link your documentation about spinning up testing clusters to `workflow.md`.

2017-06-22 22:25 UTC, jagajaga requested changes

2017-06-22 22:25 UTC, jagajaga commented on workflow.md
> +  into `master`. Sometimes, however, one wants to hand off an
Not only master.

2017-06-22 22:49 UTC, manpages commented on workflow.md
> +  into `master`. Sometimes, however, one wants to hand off an
Fixed

2017-06-22 22:52 UTC, jagajaga approved these changes

2017-06-23 08:52 UTC, domenkozar commented
Link to https://github.com/input-output-hk/internal-documentation/wiki/Deploying-clusters-from-scratch

2017-07-25 11:54 UTC, domenkozar approved these changes

2017-07-25 11:58 UTC, merged